from scrapers.impuestito import ImpuestitoScraper

ALL_SCRAPERS = [
    # Cine, Series y TV
    ImpuestitoScraper("netflix",       "Netflix"),
    ImpuestitoScraper("disney",        "Disney+"),
    ImpuestitoScraper("max",           "Max"),
    ImpuestitoScraper("amazon",        "Amazon Prime Video"),
    ImpuestitoScraper("paramount",     "Paramount+"),
    ImpuestitoScraper("appletv",       "Apple TV+"),
    ImpuestitoScraper("crunchyroll",   "Crunchyroll"),
    ImpuestitoScraper("kick",          "Kick"),
    ImpuestitoScraper("mercadolibre",  "Mercado Libre"),
    ImpuestitoScraper("mubi",          "Mubi"),
    ImpuestitoScraper("plex",          "Plex Pass"),
    ImpuestitoScraper("viki",          "Rakuten Viki Pass"),
    ImpuestitoScraper("stremio",       "Stremio"),
    ImpuestitoScraper("twitch",        "Twitch"),
    ImpuestitoScraper("vix",           "ViX Premium"),
    ImpuestitoScraper("youtube",       "YouTube Premium"),
    # Música
    ImpuestitoScraper("applemusic",    "Apple Music"),
    ImpuestitoScraper("deezer",        "Deezer"),
    ImpuestitoScraper("amazonmusic",   "Amazon Music Unlimited"),
    ImpuestitoScraper("spotify",       "Spotify"),
    ImpuestitoScraper("tidal",         "Tidal"),
    ImpuestitoScraper("yandexmusic",   "Yandex Music"),
    ImpuestitoScraper("youtubemusic",  "YouTube Music"),
    # Videojuegos
    ImpuestitoScraper("applearcade",   "Apple Arcade"),
    ImpuestitoScraper("chess",         "Chess.com"),
    ImpuestitoScraper("eaplay",        "EA Play"),
    ImpuestitoScraper("exitlag",       "ExitLag"),
    ImpuestitoScraper("faceit",        "FACEIT"),
    ImpuestitoScraper("ffxiv",         "Final Fantasy XIV"),
    ImpuestitoScraper("geforcenow",    "GeForce Now"),
    ImpuestitoScraper("geoguessr",     "Geoguessr"),
    ImpuestitoScraper("iracing",       "iRacing"),
    ImpuestitoScraper("justdance",     "Just Dance Now"),
    ImpuestitoScraper("minecraft",     "Minecraft Realms"),
    ImpuestitoScraper("nintendo",      "Nintendo Switch Online"),
    ImpuestitoScraper("playstation",   "PlayStation Plus"),
    ImpuestitoScraper("ubisoft",       "Ubisoft+"),
    ImpuestitoScraper("wow",           "World of Warcraft"),
    ImpuestitoScraper("xbox",          "Xbox Game Pass"),
    # Deportes
    ImpuestitoScraper("f1tv",          "F1 TV"),
    ImpuestitoScraper("nba",           "NBA League Pass"),
    ImpuestitoScraper("nfl",           "NFL Game Pass"),
    ImpuestitoScraper("trillertv",     "Triller TV+"),
    ImpuestitoScraper("ufc",           "UFC Fight Pass"),
    ImpuestitoScraper("wwe",           "WWE Network"),
    # Chatbots IA
    ImpuestitoScraper("chatgpt",       "ChatGPT"),
    ImpuestitoScraper("claude",        "Claude"),
    ImpuestitoScraper("copilot",       "Copilot"),
    ImpuestitoScraper("gemini",        "Gemini"),
    ImpuestitoScraper("grok",          "Grok"),
    ImpuestitoScraper("perplexity",    "Perplexity"),
    ImpuestitoScraper("t3chat",        "T3.chat"),
    # Asistentes de Código IA
    ImpuestitoScraper("cursor",        "Cursor"),
    ImpuestitoScraper("githubcopilot", "GitHub Copilot"),
    ImpuestitoScraper("jetbrains",     "JetBrains"),
    ImpuestitoScraper("tabnine",       "Tabnine"),
    ImpuestitoScraper("traeai",        "TRAE AI"),
    ImpuestitoScraper("windsurf",      "Windsurf"),
    # Vibe Coding
    ImpuestitoScraper("bolt",          "Bolt"),
    ImpuestitoScraper("lovable",       "Lovable"),
    ImpuestitoScraper("v0",            "v0"),
    # Generación Visual IA
    ImpuestitoScraper("krea",          "Krea AI"),
    ImpuestitoScraper("midjourney",    "Midjourney"),
    # Hosting, Cloud y Otros
    ImpuestitoScraper("bubble",        "Bubble.io"),
    ImpuestitoScraper("github",        "GitHub"),
    ImpuestitoScraper("nicar",         "Nic.ar"),
    ImpuestitoScraper("sanity",        "Sanity"),
    ImpuestitoScraper("starlink",      "Starlink"),
    ImpuestitoScraper("supabase",      "Supabase"),
    ImpuestitoScraper("vercel",        "Vercel"),
    ImpuestitoScraper("webflow",       "Webflow"),
    # Diseño
    ImpuestitoScraper("adobe",         "Adobe Creative Cloud"),
    ImpuestitoScraper("canva",         "Canva"),
    ImpuestitoScraper("clipchamp",     "Clipchamp"),
    ImpuestitoScraper("figjam",        "FigJam"),
    ImpuestitoScraper("figma",         "Figma"),
    ImpuestitoScraper("framer",        "Framer"),
    ImpuestitoScraper("picsart",       "Picsart"),
    # Seguridad
    ImpuestitoScraper("onepassword",   "1Password"),
    ImpuestitoScraper("bitwarden",     "Bitwarden"),
    ImpuestitoScraper("nordvpn",       "NordVPN"),
    # Productividad
    ImpuestitoScraper("appleone",      "Apple One"),
    ImpuestitoScraper("capcut",        "CapCut"),
    ImpuestitoScraper("elevenlabs",    "ElevenLabs"),
    ImpuestitoScraper("gastipro",      "Gasti Pro (ARS)"),
    ImpuestitoScraper("gastitprousd",  "Gasti Pro (USD)"),
    ImpuestitoScraper("gworkspace",    "Google Workspace"),
    ImpuestitoScraper("ifttt",         "IFTTT"),
    ImpuestitoScraper("linkedin",      "LinkedIn Premium"),
    ImpuestitoScraper("microsoft365",  "Microsoft 365"),
    ImpuestitoScraper("notion",        "Notion"),
    ImpuestitoScraper("obsidian",      "Obsidian"),
    ImpuestitoScraper("proton",        "Proton"),
    ImpuestitoScraper("tradingview",   "TradingView"),
    ImpuestitoScraper("zoom",          "Zoom"),
    # Almacenamiento
    ImpuestitoScraper("icloud",        "Apple iCloud"),
    ImpuestitoScraper("dropbox",       "Dropbox"),
    ImpuestitoScraper("googleone",     "Google One"),
    ImpuestitoScraper("onedrive",      "OneDrive"),
    ImpuestitoScraper("yandex360",     "Yandex 360"),
    # Redes Sociales y Chat
    ImpuestitoScraper("discord",       "Discord"),
    ImpuestitoScraper("metaverified",  "Meta Verified"),
    ImpuestitoScraper("slack",         "Slack"),
    ImpuestitoScraper("streamlabs",    "Streamlabs"),
    ImpuestitoScraper("telegram",      "Telegram"),
    ImpuestitoScraper("twitter",       "X (Twitter)"),
    # Aprendizaje
    ImpuestitoScraper("audible",       "Amazon Audible"),
    ImpuestitoScraper("brilliant",     "Brilliant"),
    ImpuestitoScraper("busuu",         "Busuu"),
    ImpuestitoScraper("duolingo",      "Duolingo"),
    ImpuestitoScraper("kindle",        "Kindle Unlimited"),
    ImpuestitoScraper("mimo",          "Mimo"),
]

SCRAPER_MAP = {s.service_id: s for s in ALL_SCRAPERS}
